services:
  
  # LocalStack para simular SQS local
  # OBS: leia o README.md para executar os comandos necessários para criação das filas.
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./init-sqs.sh:/etc/localstack/init-sqs.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 5
    command: ["/bin/sh", "-c", "chmod +x /etc/localstack/init-sqs.sh && /etc/localstack/init-sqs.sh && exec localstack"]
    network_mode: host
  
  fiap-video-processamento:
    depends_on: 
      - localstack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PATH_PROCESSAR=/arquivos/processar/
      - PATH_PROCESSADOS=/arquivos/processados/
      - QUEUE_PROCESSADOS=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/processados
      - QUEUE_PROCESSAR=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/processar
      - QUARKUS_SQS_ENDPOINT_OVERRIDE=http://localhost:4566
      - QUARKUS_SQS_AWS_CREDENTIALS_TYPE=static
    volumes:
      - /home/jackson/arquivos:/arquivos
    network_mode: host
