services:
  
  # LocalStack para simular SQS local
  # OBS: leia o README.md para executar os comandos necessários para criação das filas.
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
  
  fiap-video-processamento:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PATH_PROCESSAR=/arquivos/processar/
      - PATH_PROCESSADOS=/arquivos/processados/
      - QUEUE_PROCESSADOS=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/processados
      - QUEUE_PROCESSAR=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/processar
    volumes:
      - /home/jackson/arquivos:/arquivos
