services:
  
  # LocalStack para simular SQS local
  # OBS: leia o README.md para executar os comandos necessários para criação das filas.
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
